# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0002_auto_20180512_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='tag',
            new_name='tags',
        ),
    ]
